services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    secrets:
      - stripe_api_key

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"

secrets:
  stripe_api_key:
    file: ./secrets/stripe_api_key.txt
