services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    secrets:
      - stripe_api_key
      - one_month_subscription_price_id
      - six_month_subscription_price_id
      - twelve_month_subscription_price_id

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"

secrets:
  stripe_api_key:
    file: ./secrets/stripe_api_key.txt
  one_month_subscription_price_id:
    file: ./secrets/one_month_price_id.txt
  six_month_subscription_price_id:
    file: ./secrets/six_month_price_id.txt
  twelve_month_subscription_price_id:
  file: ./secrets/twelve_month_price_id.txt
