# Generated by Django 5.2.5 on 2025-08-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Exercise')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(verbose_name='Sets')),
                ('reps', models.PositiveSmallIntegerField(verbose_name='Repetitions')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('pk', models.CompositePrimaryKey('day_of_week', 'week_of_plan', 'workout_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3, verbose_name='Day of Week')),
                ('week_of_plan', models.PositiveSmallIntegerField(verbose_name='Week of Training Plan')),
                ('superset_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.workout')),
            ],
        ),
    ]
