# Generated by Django 5.2.5 on 2025-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.AddField(
            model_name='exercise',
            name='area_of_focus',
            field=models.CharField(choices=[('CHE', 'Chest'), ('BAC', 'Back'), ('SHO', 'Shoulders'), ('BIC', 'Biceps'), ('TRI', 'Triceps'), ('LEG', 'Legs'), ('COR', 'Core')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='instructions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='workout',
            name='subnotes',
            field=models.TextField(blank=True, null=True, verbose_name='More Details'),
        ),
    ]
