# Generated by Django 5.2.5 on 2025-08-27 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_exercise_description_exercise_area_of_focus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Program Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('training_type', models.CharField(choices=[('PBU', 'Power Building'), ('BBU', 'Body Building'), ('PLI', 'Power Lifting'), ('FLE', 'Flexibility'), ('CAL', 'Calisthenics')], max_length=3)),
                ('length_in_weeks', models.PositiveSmallIntegerField(verbose_name='Length in Weeks')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('flat_discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Flat Discount')),
                ('percentage_discount', models.FloatField(blank=True, null=True, verbose_name='Percentage Discount')),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('pk', models.CompositePrimaryKey('day_of_week', 'week_of_plan', 'exercise_id', 'program_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('reps', models.PositiveSmallIntegerField(verbose_name='Exercise Repetitions')),
                ('sets', models.PositiveSmallIntegerField(verbose_name='Exercise Sets')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3, verbose_name='Day of Week')),
                ('week_of_plan', models.PositiveSmallIntegerField(verbose_name='Week of Training Plan')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('environment', models.CharField(choices=[('HO', 'Home'), ('GY', 'Gym')], max_length=2, verbose_name='Training Environment')),
                ('superset_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='exercises',
            field=models.ManyToManyField(through='gym.ProgramExercise', to='gym.exercise'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('transaction_id', models.CharField(max_length=255, verbose_name='Transaction ID')),
                ('status', models.CharField(max_length=40, verbose_name='Status')),
                ('transaction_type', models.CharField(max_length=40, verbose_name='Transaction Type')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gym.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='users',
            field=models.ManyToManyField(through='gym.Subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
