# Generated by Django 5.2.6 on 2025-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_program_remove_workout_exercise_programexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexercise',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
