# Generated by Django 5.2.7 on 2025-10-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_programexercise_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programexercise',
            name='pk',
        ),
        migrations.AddField(
            model_name='programexercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='gym.program'),
        ),
        migrations.AddConstraint(
            model_name='programexercise',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'week_of_plan', 'exercise', 'program'), name='unique_program_exercise_schedule'),
        ),
    ]
